apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-config-pvc
spec:
  storageClassName: ""
  volumeName: jf-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-config-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/HDD/local-jellyfin-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - epsilon
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-cache-pvc
spec:
  storageClassName: "freenas-nfs-csi"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-truenas-media-pvc
spec:
  storageClassName: ""
  volumeName: jf-truenas-media-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20T
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-truenas-media-pv
spec:
  capacity:
    storage: 20T
  accessModes:
    - ReadWriteMany
  nfs:
    server: galactus.avril
    path: /mnt/low-resiliency-with-read-cache/ombi-data/
# ---
# # https://forum.jellyfin.org/t-could-not-apply-migration-migrateactivitylogdatabase
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jf-config
# spec:
#   capacity:
#     storage: "100M"
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   storageClassName: local-storage
#   local:
#     path: /mnt/NEW_BERTHA/local-jellyfin-config
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - rasnu2
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jf-config-pvc
# spec:
#   storageClassName: ""
#   volumeName: jf-config
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: "100M"
