apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackjack-app-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/scubbo/homelab-configuration.git
    targetRevision: HEAD
    path: app-of-apps

  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
