apiVersion: v1
kind: PersistentVolume
metadata:
  name: dropbox-backup-pv
spec:
  capacity:
    storage: {{ .Values.nfs.capacity }}
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dropbox-backup-pvc
spec:
  storageClassName: ""
  volumeName: dropbox-backup-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.capacity }}
