apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tdarr.fullname" . }}-local-plugins
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "plugins/*.js").AsConfig | indent 2 }}
