apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdarr.fullname" . }}
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webui
      port: {{ .Values.service.webUIPort }}
      targetPort: webui
      protocol: TCP
    - name: server
      port: {{ .Values.service.serverPort }}
      targetPort: server
      protocol: TCP
  selector:
    {{- include "tdarr.selectorLabels" . | nindent 4 }}
