apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config-pvc
spec:
  storageClassName: {{ .Values.persistence.config.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-truenas-media-pvc
spec:
  storageClassName: ""
  volumeName: tdarr-truenas-media-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-truenas-media-pv
spec:
  capacity:
    storage: {{ .Values.persistence.media.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.persistence.media.server }}
    path: {{ .Values.persistence.media.path }}
