apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: dns-health
  namespace: prometheus
  labels:
    release: prometheus
spec:
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.prometheus.svc:9115
  module: dns_udp
  interval: 30s
  scrapeTimeout: 10s
  targets:
    staticConfig:
      static:
        - 192.168.1.1:53
        - 192.168.1.1:5353
      labels:
        probe_type: dns
