apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: wan-health
  namespace: prometheus
  labels:
    release: prometheus
spec:
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.prometheus.svc:9115
  module: tcp_connect
  interval: 10s
  scrapeTimeout: 5s
  targets:
    staticConfig:
      static:
        - 8.8.8.8:443
      labels:
        probe_type: wan
