apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "arr-stack.fullname" . }}-truenas-data-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 20T
  accessModes:
    - ReadWriteMany
  nfs:
    server: galactus.avril
    path: /mnt/low-resiliency-with-read-cache/ombi-data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr-stack.fullname" . }}-truenas-data-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  volumeName: {{ include "arr-stack.fullname" . }}-truenas-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20T
{{- range tuple "readarr" "prowlarr" "nzbget" "sabnzbd" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr-stack.fullname" $ }}-{{.}}-config-pvc
spec:
  storageClassName: "freenas-nfs-csi"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
---
# Split this out so that we can use a different storage class for radarr
{{ if .Values.radarr.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr-stack.fullname" $ }}-radarr-config-iscsi-pvc
spec:
  storageClassName: "freenas-iscsi-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end }}

{{ if .Values.ombi.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr-stack.fullname" $ }}-ombi-config-iscsi-pvc
spec:
  storageClassName: "freenas-iscsi-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end}}

{{ if .Values.sonarr.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr-stack.fullname" $ }}-sonarr-config-iscsi-pvc
spec:
  storageClassName: "freenas-iscsi-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end}}

{{ if .Values.readarr.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr-stack.fullname" $ }}-readarr-config-iscsi-pvc
spec:
  storageClassName: "freenas-iscsi-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end}}

{{ if .Values.prowlarr.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr-stack.fullname" $ }}-prowlarr-config-iscsi-pvc
spec:
  storageClassName: "freenas-iscsi-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end}}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "arr-stack.fullname" . }}-truenas-usenet-downloads-pv
spec:
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  nfs:
    server: galactus.avril
    path: /mnt/low-resiliency-with-read-cache/ombi-data/usenet
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arr-stack.fullname" . }}-truenas-usenet-downloads-pvc
spec:
  storageClassName: ""
  volumeName: {{ include "arr-stack.fullname" . }}-truenas-usenet-downloads-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T
